name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Install CreoIDE
        run: |
          sudo apt-get update
          # Assuming CreoIDE is available from a repository
          sudo add-apt-repository 'deb [arch=amd64] http://example.com/creoide-repo bionic main'
          sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys ABCDEFGH
          sudo apt-get update
          sudo apt-get install -y creoide
          
          # Alternatively, if CreoIDE is available as a downloadable package
          # wget http://example.com/creoide.deb
          # sudo dpkg -i creoide.deb
          # sudo apt-get install -f
          
          # Verify installation
          if ! command -v creoide &> /dev/null; then
            echo "CreoIDE installation failed or command not found"
            exit 1
          fi

      - name: Authenticate CreoIDE with GitHub
        env:
          GITHUB_USERNAME: ${{ secrets.GITHUB_USERNAME }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: creoide auth github -u $GITHUB_USERNAME -p $GITHUB_TOKEN

      - name: Create CreoLang Project
        run: creoide createProject MyCreoProject

      - name: Add File to Project
        run: |
          echo "/* CreoLang code */" > main.creo
          creoide addFile MyCreoProject main.creo "/* CreoLang code */"

      - name: Compile CreoLang Code
        run: creoide compile main.creo main

      - name: Run Compiled Code
        run: creoide run main

      - name: Build CreoLang Project
        run: creoide buildProject MyCreoProject release

      - name: Test CreoLang Project
        run: creoide testProject MyCreoProject unit-tests

      - name: Deploy CreoLang Project
        run: |
          declare -A deployOptions=(
            ["target"]="server"
            ["mode"]="auto-scaling"
          )
          creoide deployProject MyCreoProject production "$(declare -p deployOptions)"

      - name: Clean Project
        run: creoide clean MyCreoProject

      - name: Upload Test Results
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: test-results/

      - name: Upload Coverage Report
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: coverage/

      - name: Notify on Failure
        if: failure()
        run: |
          echo "Build failed. Sending notification..."
          # Add your notification command here